# Generated by Django 3.0.7 on 2020-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dtmap',
            fields=[
                ('id', models.IntegerField(help_text='UID必须唯一！例如：00001234', primary_key=True, serialize=False, unique=True, verbose_name='个人UID')),
                ('name', models.TextField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('time', models.TimeField(blank=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': 'ID',
                'verbose_name_plural': '注册用户查询',
            },
        ),
    ]
